Await turnOn if not completed + Throw when turnOn has not been called yet
91team/computer pull request #15
Opened 2021-12-06 14:23 UTC by ikbendewilliam

Fixes #14 
Fixes typo `workersCount` should *not* be more than 0 -> `workersCount` should be more than 0

2021-12-06 14:31 UTC, NicolaVerbeeck requested changes

2021-12-06 14:31 UTC, NicolaVerbeeck commented on lib/src/computer.dart
> +  Completer? _completer;
Does not describe what the completer is for

2021-12-06 14:31 UTC, NicolaVerbeeck commented on lib/src/computer.dart
> +    _completer = Completer<void>();
add assert that checks > 0

2021-12-06 14:31 UTC, NicolaVerbeeck commented on lib/src/computer.dart
> +    _completer = Completer<void>();
check if we are not turning on twice

2021-12-06 14:31 UTC, NicolaVerbeeck commented on lib/src/computer.dart
> +  /// Throws when turnOn has not been called, awaits when turnOn has been called, but not yet finished
Update wording `awaits when turnOn has been called`

2021-12-06 14:31 UTC, NicolaVerbeeck commented on lib/src/computer.dart
> +    if (_completer?.isCompleted == false) _completer!.completeError('Computer turned off');
Turn off does not reset completer

2021-12-06 14:39 UTC, NicolaVerbeeck commented on lib/src/computer.dart
> +    _completer = null;
Should we wait for turn off to complete before marking this. and/or wait for turn on to complete if it was running at that time

2021-12-28 16:10 UTC, ikbendewilliam commented
@dmitriismitnov @91team can you review please?

2021-12-28 22:05 UTC, dmitriismitnov commented
@ikbendewilliam Hi =) I will review this pr 04th January 2021. Happy New Year 🎆

2021-12-28 22:06 UTC, dmitriismitnov commented
@ikbendewilliam Oh, thanks for your pr!

2021-12-28 22:07 UTC, ikbendewilliam commented
@dmitriismitnov great! Thank you! Happy new year 🥳

2022-01-02 11:47 UTC, dmitriismitnov commented
@ikbendewilliam Hi. Unfortunately, I cannot approve this PR.

This PR conflicts with https://github.com/91team/computer/pull/12 therefore the tests are not valid.
For more details, please pay attention to https://github.com/91team/computer/pull/12

In Future, for resolve this collision I will create some mechanism for configure various behaviour.
If you want to be involved, welcome =)

2022-01-03 05:24 UTC, closed without merging

2022-01-05 22:43 UTC, ikbendewilliam commented
I see, #12 was merged after I started on this. I'm not sure if that PR fixes all issues, I'll be checking that when I've got the time 👍